### ISSUE TITLE
calculate_yaku breaks after TSUMO

### ISSUE THREAD

**Issue by ktc312** [rasca0027/Mahjong4RL#139]
```
------ 
Player: Hao
Jikaze: PEI
Drawn tile is: 🀑
Please select action using number:
0: Action.NOACT
4: Action.TSUMO
4
Player TSUMO!
Traceback (most recent call last):
  File "run_game.py", line 5, in <module>
    game.start_game()
  File "/Users/Leo/Documents/Mahjong4RL/mahjong/game.py", line 47, in start_game
    renchan, kyotaku, honba = self.current_kyoku.start()
  File "/Users/Leo/Documents/Mahjong4RL/mahjong/kyoku.py", line 420, in start
    han, fu = self.calculate_yaku(tsumo)
  File "/Users/Leo/Documents/Mahjong4RL/mahjong/kyoku.py", line 386, in calculate_yaku
    winner = self.winners[0]  # temporary
IndexError: list index out of range
```

**Comment by rasca0027** [comment]
Should be fixed now?
